// Auto-generated by scripts/gen_coefficients.py — do not edit manually
// Butterworth 8-order bandpass 8-30 Hz @ 1000 Hz
// 8 Second-Order Sections (Direct Form II Transposed)

#define N_SOS_SECTIONS 8

static const float SOS_B0[] = {0.0000000004f, 1.0000000000f, 1.0000000000f, 1.0000000000f, 1.0000000000f, 1.0000000000f, 1.0000000000f, 1.0000000000f};
static const float SOS_B1[] = {0.0000000007f, 2.0000000000f, 2.0000000000f, 2.0000000000f, -2.0000000000f, -2.0000000000f, -2.0000000000f, -2.0000000000f};
static const float SOS_B2[] = {0.0000000004f, 1.0000000000f, 1.0000000000f, 1.0000000000f, 1.0000000000f, 1.0000000000f, 1.0000000000f, 1.0000000000f};
// a0 is always 1 (normalised); a1, a2 are negated for Direct Form II
static const float SOS_A1[] = {-1.8273598430f, -1.8381353827f, -1.8601366281f, -1.8891954199f, -1.9320314661f, -1.9244236683f, -1.9617188679f, -1.9860143055f};
static const float SOS_A2[] = {0.8489643377f, 0.8509443473f, 0.8892901014f, 0.8953500188f, 0.9357477885f, 0.9586072812f, 0.9645701412f, 0.9885636347f};
