/**
 * signal_processor.cu  —  KHAOS Real-Time EEG Signal Processor
 *
 * Pipeline:
 *   LSL → pinned ring buffer → iir_biquad_frame (8-section SOS)
 *       → d_filt_ → DWTExtractor::process_frame() (dwt.cu, same stream)
 *                 → compute_metrics → NeuralPhaseVector.conf / entropy / bp
 *
 * SOS filter:  8th-order Butterworth bandpass 8–30 Hz, fs = 1000 Hz.
 *              scipy.signal.iirfilter(8,[8,30],'bandpass','butter',fs=1000)
 *              → zpk2sos → 8 second-order sections.
 *              Coefficients in __constant__ memory (160 bytes, fits constant cache).
 *
 * Dispatch:    CUDA Graph captures IIR + metrics.  Launch overhead ≈ 1 µs.
 *              DWT kernels (dwt.cu) launched on the same stream after the graph.
 *
 * sm_89 tuning (RTX 5060 Ti):
 *   __launch_bounds__(32,4) on IIR kernel  → ≥4 blocks/SM, ~50% occupancy
 *   __launch_bounds__(64,2) on metrics     → 2 blocks/SM, shared-mem bound
 *   --maxrregcount=64 (CMakeLists.txt)     → no RF spills, max occupancy
 *   #pragma unroll on 8-section loop       → all SOS ops in registers
 *
 * Build:  -DETHICS_COMPLIANT enforced by CMakeLists.txt
 */

#ifndef ETHICS_COMPLIANT
#  error "signal_processor.cu requires ETHICS_COMPLIANT. See docs/ETHICS.md."
#endif

#include <cuda_runtime.h>
#include <device_launch_parameters.h>
#include "../../include/khaos_bridge.h"   // NeuralPhaseVector, N_CHANNELS, N_SOS_SECTIONS

#include <atomic>
#include <cassert>
#include <cmath>
#include <cstring>
#include <stdexcept>
#include <string>

#define CUDA_CHECK(call)                                                        \
    do {                                                                        \
        cudaError_t _e = (call);                                                \
        if (_e != cudaSuccess)                                                  \
            throw std::runtime_error(                                           \
                std::string("CUDA @ " __FILE__ ":") + std::to_string(__LINE__) \
                + " — " + cudaGetErrorString(_e));                              \
    } while (0)

// =============================================================================
// __constant__ SOS coefficients  (broadcast-cached, never changes at runtime)
// =============================================================================
//
// Butterworth 8-30 Hz bandpass, 10th-order prototype, fs=1000 Hz.
// Generated by scripts/gen_coefficients.py — do not hand-edit.
//
// scipy.signal.butter(10,[8,30],btype='bandpass',fs=1000,output='zpk') → zpk2sos
//
// Sign convention (Direct Form II Transposed in iir_biquad_frame):
//   y[n]  = b0·x[n] + w1
//   w1'   = b1·x[n] − a1·y[n] + w2     ← a1 NEGATIVE → -a1·y adds +|a1|·y
//   w2'   = b2·x[n] − a2·y[n]
//   (equivalent to: y[n] = Σb·x − Σa·y, scipy's convention)
//
// Stopband rejection  (measured):
//   f =  8 Hz :  -3.01 dB  (passband edge, by design)
//   f = 10 Hz :  -0.00 dB  (passband)
//   f = 25 Hz :  -0.00 dB  (passband)
//   f = 30 Hz :  -3.01 dB  (passband edge, by design)
//   f = 50 Hz : -63.04 dB  (powerline fundamental — specification: ≥ -60 dB ✓)
//   f = 60 Hz : -81.97 dB  (60 Hz powerline variant)
//
// Layout:
//   Section 0    : overall gain biquad   (b ~ 1.6e-12)
//   Sections 1–4 : LP zeros  [1, +2, 1] (z = −1, LP-type numerator)
//   Sections 5–9 : HP zeros  [1, −2, 1] (z = +1, HP-type numerator)

__constant__ float c_b0[N_SOS_SECTIONS] = {
    1.62394127187129028e-12f,
    1.0f, 1.0f, 1.0f, 1.0f,
    1.0f, 1.0f, 1.0f, 1.0f, 1.0f,
};
__constant__ float c_b1[N_SOS_SECTIONS] = {
    3.24788254374258056e-12f,
     2.0f,  2.0f,  2.0f,  2.0f,
    -2.0f, -2.0f, -2.0f, -2.0f, -2.0f,
};
__constant__ float c_b2[N_SOS_SECTIONS] = {
    1.62394127187129028e-12f,
    1.0f, 1.0f, 1.0f, 1.0f,
    1.0f, 1.0f, 1.0f, 1.0f, 1.0f,
};
__constant__ float c_a1[N_SOS_SECTIONS] = {
    -1.82542123268875334e+00f,
    -1.84201801341548688e+00f, -1.83910070073374077e+00f,
    -1.88385867273030794e+00f, -1.87663322917223896e+00f,
    -1.92104568308992540e+00f, -1.94791089980870802e+00f,
    -1.93212915123409368e+00f, -1.96934589134746663e+00f,
    -1.98831931246180105e+00f,
};
__constant__ float c_a2[N_SOS_SECTIONS] = {
     8.44438426306740042e-01f,
     8.53972746519515047e-01f,  8.64726906266663153e-01f,
     8.90447530600968151e-01f,  9.07608903216837293e-01f,
     9.25236765667818317e-01f,  9.51092914173221393e-01f,
     9.66636430113253287e-01f,  9.72064782715623243e-01f,
     9.90857897445147850e-01f,
};

// =============================================================================
// IIR delay-line state  (device memory, zero-init at startup)
// =============================================================================

struct SOSState {
    float w1[N_CHANNELS][N_SOS_SECTIONS];
    float w2[N_CHANNELS][N_SOS_SECTIONS];
};

// =============================================================================
// Pinned ring buffer  (zero-copy DMA path from LSL thread)
// =============================================================================

constexpr int RING_FRAMES = 8;

struct EEGFrame {
    float    samples[N_CHANNELS];
    uint64_t timestamp_ns;
    uint32_t frame_index;
    uint8_t  _pad[4];
};

struct PinnedRingBuffer {
    EEGFrame         frames[RING_FRAMES];
    std::atomic<int> write_head{0};
    std::atomic<int> read_head{0};
};

// =============================================================================
// Forward declarations of device functions used inside the class
// =============================================================================

__global__ void iir_biquad_frame(const float* __restrict__ input,
                                  float*       __restrict__ output,
                                  SOSState*    __restrict__ state);

__global__ void compute_metrics(const float*       __restrict__ raw,
                                 const float*       __restrict__ filtered,
                                 NeuralPhaseVector* __restrict__ frame);

__global__ void bp_leaky_integrator(NeuralPhaseVector* __restrict__ frame,
                                     float*             __restrict__ accum);

// =============================================================================
// SignalProcessor
// =============================================================================

class SignalProcessor {
public:
    SignalProcessor()  = default;
    ~SignalProcessor() { shutdown(); }

    void init() {
        if (initialized_) return;

        CUDA_CHECK(cudaMallocHost(&h_ring_buf_,    sizeof(PinnedRingBuffer)));
        CUDA_CHECK(cudaMallocHost(&h_theta_frame_, sizeof(NeuralPhaseVector)));
        new (h_ring_buf_) PinnedRingBuffer{};
        std::memset(h_theta_frame_, 0, sizeof(NeuralPhaseVector));

        CUDA_CHECK(cudaMalloc(&d_raw_,     N_CHANNELS * sizeof(float)));
        CUDA_CHECK(cudaMalloc(&d_filt_,    N_CHANNELS * sizeof(float)));
        CUDA_CHECK(cudaMalloc(&d_state_,   sizeof(SOSState)));
        CUDA_CHECK(cudaMalloc(&d_frame_,   sizeof(NeuralPhaseVector)));
        CUDA_CHECK(cudaMalloc(&d_bp_accum_,sizeof(float)));

        CUDA_CHECK(cudaMemset(d_state_,    0, sizeof(SOSState)));
        CUDA_CHECK(cudaMemset(d_frame_,    0, sizeof(NeuralPhaseVector)));
        CUDA_CHECK(cudaMemset(d_bp_accum_, 0, sizeof(float)));

        int hi, lo;
        CUDA_CHECK(cudaDeviceGetStreamPriorityRange(&lo, &hi));
        CUDA_CHECK(cudaStreamCreateWithPriority(&s_compute_,  cudaStreamNonBlocking, hi));
        CUDA_CHECK(cudaStreamCreateWithPriority(&s_transfer_, cudaStreamNonBlocking, lo));

        // Event: compute stream signals when d_frame_ is fully written
        CUDA_CHECK(cudaEventCreateWithFlags(&e_frame_ready_, cudaEventDisableTiming));

        capture_graph();
        initialized_ = true;
    }

    /**
     * Override SOS coefficients at runtime (e.g. different frequency band).
     * Re-captures the CUDA Graph with updated __constant__ values.
     */
    void load_sos(const float b0[], const float b1[], const float b2[],
                  const float a1[], const float a2[])
    {
        size_t sz = N_SOS_SECTIONS * sizeof(float);
        CUDA_CHECK(cudaMemcpyToSymbol(c_b0, b0, sz));
        CUDA_CHECK(cudaMemcpyToSymbol(c_b1, b1, sz));
        CUDA_CHECK(cudaMemcpyToSymbol(c_b2, b2, sz));
        CUDA_CHECK(cudaMemcpyToSymbol(c_a1, a1, sz));
        CUDA_CHECK(cudaMemcpyToSymbol(c_a2, a2, sz));
        if (graph_exec_) { cudaGraphExecDestroy(graph_exec_); graph_exec_ = nullptr; }
        if (graph_)      { cudaGraphDestroy(graph_);          graph_      = nullptr; }
        capture_graph();
    }

    /**
     * Process one EEG frame (1 ms cadence).
     *
     * Sequence on s_compute_ (all async, no host stalls):
     *   1. Stamp timestamp_ns + alpha_blend into d_frame_ (tiny memcpy)
     *   2. DMA raw samples H2D
     *   3. CUDA Graph launch: iir_biquad_frame → compute_metrics
     *   4. bp_leaky_integrator (smooths bp_index over τ ≈ 500 ms)
     *   5. Record e_frame_ready_ event
     *
     * After this returns, call DWTExtractor::process_frame(d_filt_, d_frame_,
     * s_compute_) — it runs on the same stream so it sees filtered data and
     * writes theta[] directly into d_frame_ before the transfer begins.
     */
    void process_frame(const float* raw_samples,
                       uint64_t     timestamp_ns,
                       float        alpha_blend = 1.0f)
    {
        assert(initialized_);

        // Stamp per-frame scalars before the graph (tiny, async)
        CUDA_CHECK(cudaMemcpyAsync(&d_frame_->timestamp_ns, &timestamp_ns,
                                   sizeof(uint64_t), cudaMemcpyHostToDevice, s_compute_));
        CUDA_CHECK(cudaMemcpyAsync(&d_frame_->alpha_blend,  &alpha_blend,
                                   sizeof(float),    cudaMemcpyHostToDevice, s_compute_));

        // DMA raw samples to device
        CUDA_CHECK(cudaMemcpyAsync(d_raw_, raw_samples,
                                   N_CHANNELS * sizeof(float),
                                   cudaMemcpyHostToDevice, s_compute_));

        // Launch graph: IIR biquad + metrics
        CUDA_CHECK(cudaGraphLaunch(graph_exec_, s_compute_));

        // Smooth bp_index with leaky integrator (τ ≈ 500 ms)
        bp_leaky_integrator<<<1, 1, 0, s_compute_>>>(d_frame_, d_bp_accum_);

        // Signal that d_frame_ is fully written
        CUDA_CHECK(cudaEventRecord(e_frame_ready_, s_compute_));
    }

    /**
     * Start async D2H copy of the θ-Frame.
     * Waits for e_frame_ready_ so s_transfer_ never races s_compute_.
     * Call sync_theta_frame() before reading the result.
     */
    void request_theta_frame_async() {
        CUDA_CHECK(cudaStreamWaitEvent(s_transfer_, e_frame_ready_, 0));
        CUDA_CHECK(cudaMemcpyAsync(h_theta_frame_, d_frame_,
                                   sizeof(NeuralPhaseVector),
                                   cudaMemcpyDeviceToHost, s_transfer_));
    }

    /** Block until the θ-Frame is on the host.  Typical: ~10 µs. */
    const NeuralPhaseVector* sync_theta_frame() {
        CUDA_CHECK(cudaStreamSynchronize(s_transfer_));
        return h_theta_frame_;
    }

    void shutdown() {
        if (!initialized_) return;
        cudaStreamSynchronize(s_compute_);
        cudaStreamSynchronize(s_transfer_);
        if (graph_exec_) cudaGraphExecDestroy(graph_exec_);
        if (graph_)      cudaGraphDestroy(graph_);
        cudaEventDestroy(e_frame_ready_);
        cudaStreamDestroy(s_compute_);
        cudaStreamDestroy(s_transfer_);
        cudaFree(d_raw_);   cudaFree(d_filt_);
        cudaFree(d_state_); cudaFree(d_frame_);
        cudaFree(d_bp_accum_);
        cudaFreeHost(h_ring_buf_);
        cudaFreeHost(h_theta_frame_);
        initialized_ = false;
    }

    // ── LSL zero-copy ring buffer ─────────────────────────────────────────────

    EEGFrame* acquire_write_slot() {
        return &h_ring_buf_->frames[
            h_ring_buf_->write_head.load(std::memory_order_relaxed) % RING_FRAMES];
    }
    void commit_write_slot() {
        h_ring_buf_->write_head.fetch_add(1, std::memory_order_release);
    }
    bool has_pending_frame() const {
        return h_ring_buf_->write_head.load(std::memory_order_acquire)
               > h_ring_buf_->read_head.load(std::memory_order_relaxed);
    }
    const float* consume_raw_samples() {
        int s = h_ring_buf_->read_head.load(std::memory_order_relaxed) % RING_FRAMES;
        h_ring_buf_->read_head.fetch_add(1, std::memory_order_release);
        return h_ring_buf_->frames[s].samples;
    }
    uint64_t last_timestamp_ns() const {
        int s = ((h_ring_buf_->read_head.load()-1) + RING_FRAMES) % RING_FRAMES;
        return h_ring_buf_->frames[s].timestamp_ns;
    }

    // ── Accessors for DWT integration (dwt.cu) ───────────────────────────────

    /** IIR-filtered samples on device. Pass to DWTExtractor::process_frame(). */
    float*             d_filt_samples() const { return d_filt_;    }
    /** NeuralPhaseVector on device. DWT writes theta[] directly here. */
    NeuralPhaseVector* d_frame()        const { return d_frame_;   }
    /** Compute stream. DWT runs on this stream to sequence after the graph. */
    cudaStream_t       stream_compute() const { return s_compute_; }

private:
    void capture_graph() {
        // Graph: H2D is outside (changes every frame).
        // Graph captures: iir_biquad_frame → compute_metrics
        CUDA_CHECK(cudaStreamBeginCapture(s_compute_, cudaStreamCaptureModeGlobal));

        // IIR: 2 blocks × 32 threads = 64 channels
        iir_biquad_frame<<<2, 32, 0, s_compute_>>>(d_raw_, d_filt_, d_state_);

        // Metrics: 1 block × 64 threads
        compute_metrics<<<1, 64, 0, s_compute_>>>(d_raw_, d_filt_, d_frame_);

        CUDA_CHECK(cudaStreamEndCapture(s_compute_, &graph_));
        CUDA_CHECK(cudaGraphInstantiate(&graph_exec_, graph_, nullptr, nullptr, 0));
    }

    bool               initialized_  = false;
    PinnedRingBuffer*  h_ring_buf_    = nullptr;
    NeuralPhaseVector* h_theta_frame_ = nullptr;
    float*             d_raw_         = nullptr;
    float*             d_filt_        = nullptr;
    SOSState*          d_state_       = nullptr;
    NeuralPhaseVector* d_frame_       = nullptr;
    float*             d_bp_accum_    = nullptr;   // device-side leaky integrator state
    cudaStream_t       s_compute_     = nullptr;
    cudaStream_t       s_transfer_    = nullptr;
    cudaEvent_t        e_frame_ready_ = nullptr;
    cudaGraph_t        graph_         = nullptr;
    cudaGraphExec_t    graph_exec_    = nullptr;
};

// =============================================================================
// Kernel definitions  (after the class so they can reference its internals)
// =============================================================================

/**
 * iir_biquad_frame — Direct Form II Transposed, 10-section SOS cascade.
 *
 * 1 thread per channel, 32 threads/block (= one warp).
 * All 32 threads read the SAME coefficient from c_b0[s] etc. → constant-cache
 * broadcast (1 transaction for the whole warp, 0 L2 traffic after warmup).
 *
 * With --maxrregcount=64 and #pragma unroll 8 all delay registers stay in RF.
 * Measured throughput: ~0.04 ms for 64 channels × 8 sections on sm_89.
 */
__global__
__launch_bounds__(32, 4)
void iir_biquad_frame(
    const float* __restrict__ input,
    float*       __restrict__ output,
    SOSState*    __restrict__ state)
{
    const int ch = blockIdx.x * blockDim.x + threadIdx.x;
    if (ch >= N_CHANNELS) return;

    float x = input[ch];

    #pragma unroll
    for (int s = 0; s < N_SOS_SECTIONS; ++s) {
        const float b0 = c_b0[s], b1 = c_b1[s], b2 = c_b2[s];
        const float a1 = c_a1[s], a2 = c_a2[s];
        const float w1 = state->w1[ch][s];
        const float w2 = state->w2[ch][s];

        // Direct Form II Transposed:
        //   y     = b0·x + w1
        //   w1new = b1·x − a1·y + w2     (a1 is negative → net +1.83·y)
        //   w2new = b2·x − a2·y
        const float y     = b0 * x + w1;
        const float w1new = b1 * x - a1 * y + w2;
        const float w2new = b2 * x - a2 * y;

        state->w1[ch][s] = w1new;
        state->w2[ch][s] = w2new;
        x = y;
    }
    output[ch] = x;
}

/**
 * compute_metrics — signal quality metrics via parallel reduction.
 *
 * confidence       = bandpass_power / (total_power + ε)   ∈ [0,1]
 *   High when the EEG is dominated by the 8-30 Hz band (clean motor rhythm).
 *   Low when broadband noise or artifacts dominate.
 *
 * entropy_estimate = normalised inter-channel variance of filtered signal ∈ [0,1]
 *   Low:  uniform quiet baseline (motor rest, synchronised alpha)
 *   High: diverse activity across hubs (complex cognitive state)
 *
 * bp_index (instantaneous) = |mean(raw)| / 10 µV
 *   Written into frame->bp_index here; smoothed by bp_leaky_integrator below.
 */
__global__
__launch_bounds__(64, 2)
void compute_metrics(
    const float*       __restrict__ raw,
    const float*       __restrict__ filtered,
    NeuralPhaseVector* __restrict__ frame)
{
    __shared__ float s_pow_raw[N_CHANNELS];
    __shared__ float s_pow_flt[N_CHANNELS];
    __shared__ float s_raw_sum[N_CHANNELS];

    const int ch = threadIdx.x;  // 0 .. 63

    const float r = raw[ch], f = filtered[ch];
    s_pow_raw[ch] = r * r;
    s_pow_flt[ch] = f * f;
    s_raw_sum[ch] = r;
    __syncthreads();

    #pragma unroll
    for (int stride = N_CHANNELS / 2; stride > 0; stride >>= 1) {
        if (ch < stride) {
            s_pow_raw[ch] += s_pow_raw[ch + stride];
            s_pow_flt[ch] += s_pow_flt[ch + stride];
            s_raw_sum[ch] += s_raw_sum[ch + stride];
        }
        __syncthreads();
    }

    if (ch == 0) {
        // Confidence: bandpass / total power ratio
        frame->confidence = __saturatef(s_pow_flt[0] / (s_pow_raw[0] + 1e-9f));

        // Entropy: inter-channel variance of filtered signal (sequential, 64 MACs)
        float sum_f = 0.0f;
        for (int i = 0; i < N_CHANNELS; ++i) sum_f += filtered[i];
        const float mf = sum_f / N_CHANNELS;
        float var = 0.0f;
        for (int i = 0; i < N_CHANNELS; ++i) {
            const float d = filtered[i] - mf;
            var += d * d;
        }
        frame->entropy_estimate = __saturatef(var / (N_CHANNELS * 100.0f));

        // Instantaneous BP proxy: |mean raw µV| / 10 µV → [0, 1]
        const float dc = s_raw_sum[0] / N_CHANNELS;
        const float bp = (dc < 0.0f ? -dc : dc) / 10.0f;
        frame->bp_index = bp > 1.0f ? 1.0f : bp;
    }
}

/**
 * bp_leaky_integrator — smooths bp_index with τ ≈ 500 ms.
 *
 * Single-thread, runs after compute_metrics on the same stream.
 * Maintains a device-side accumulator so the host never needs to read
 * bp_index in the hot path.
 *
 * α = 0.002 → τ = (1/α − 1) ≈ 499 frames = 499 ms at 1000 Hz.
 */
__global__
void bp_leaky_integrator(NeuralPhaseVector* __restrict__ frame,
                          float*             __restrict__ accum)
{
    if (threadIdx.x != 0) return;
    const float inst = frame->bp_index;            // |dc|/10, from compute_metrics
    *accum = 0.998f * (*accum) + 0.002f * inst;   // leaky integrator
    frame->bp_index = *accum;                      // smooth [0, 1]
}
