#!/usr/bin/env python3
"""
gen_coefficients.py — KHAOS
Generates IIR SOS filter coefficients and writes them as C headers.

Usage:
    python3 scripts/gen_coefficients.py

Requires: scipy, numpy
    pip install scipy numpy
"""

import numpy as np
from scipy.signal import iirfilter, zpk2sos
import json, pathlib

FS       = 1000.0   # sample rate (Hz)
BANDPASS = (8, 30)  # mu + beta combined pass band
ORDER    = 8        # Butterworth order (= 4 SOS sections)

z, p, k = iirfilter(ORDER, [b / FS * 2 for b in BANDPASS],
                    btype="bandpass", ftype="butter", output="zpk")
sos = zpk2sos(z, p, k)   # shape: (ORDER, 6)

print(f"Generated {len(sos)}-section SOS filter "
      f"for {BANDPASS[0]}–{BANDPASS[1]} Hz @ {FS} Hz")

# ── JSON (for inspection / debugging) ────────────────────────────────────────
out_json = pathlib.Path("coefficients/sos_8_30hz.json")
out_json.parent.mkdir(exist_ok=True)
out_json.write_text(
    json.dumps({"sos": sos.tolist(), "fs": FS, "band": BANDPASS}, indent=2)
)
print(f"Saved: {out_json}")

# ── C header ──────────────────────────────────────────────────────────────────
n_sections = len(sos)
lines = []
lines.append("// Auto-generated by scripts/gen_coefficients.py — do not edit manually")
lines.append(f"// Butterworth {ORDER}-order bandpass "
             f"{BANDPASS[0]}-{BANDPASS[1]} Hz @ {int(FS)} Hz")
lines.append(f"// {n_sections} Second-Order Sections (Direct Form II Transposed)")
lines.append("")
lines.append(f"#define N_SOS_SECTIONS {n_sections}")
lines.append("")
lines.append("static const float SOS_B0[] = {" +
             ", ".join(f"{v:.10f}f" for v in sos[:, 0]) + "};")
lines.append("static const float SOS_B1[] = {" +
             ", ".join(f"{v:.10f}f" for v in sos[:, 1]) + "};")
lines.append("static const float SOS_B2[] = {" +
             ", ".join(f"{v:.10f}f" for v in sos[:, 2]) + "};")
lines.append("// a0 is always 1 (normalised); a1, a2 are negated for Direct Form II")
lines.append("static const float SOS_A1[] = {" +
             ", ".join(f"{v:.10f}f" for v in sos[:, 4]) + "};")
lines.append("static const float SOS_A2[] = {" +
             ", ".join(f"{v:.10f}f" for v in sos[:, 5]) + "};")

out_h = pathlib.Path("coefficients/sos_8_30hz.h")
out_h.write_text("\n".join(lines) + "\n")
print(f"Saved: {out_h}")

print("\nInclude in signal_processor.cu with:")
print('  #include "../../coefficients/sos_8_30hz.h"')
print("\nSOS sections:")
print(f"  {'Sec':>3}  {'b0':>14}  {'b1':>14}  {'b2':>14}  "
      f"{'a1':>14}  {'a2':>14}")
for i, s in enumerate(sos):
    print(f"  {i:>3}  {s[0]:>14.8f}  {s[1]:>14.8f}  {s[2]:>14.8f}  "
          f"  {s[4]:>14.8f}  {s[5]:>14.8f}")
